       

name: Terraform apply

on:
  workflow_dispatch:     
  push:
    branches:
      - main

jobs:
  create:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./

       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up mise
        uses: jdx/mise-action@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Install tools via mise
        run: mise install
        shell: bash
        working-directory: ${{ ./ }}  
  
      # - name: Setting up Terraform
      #   uses: hashicorp/setup-terraform@v2
        
      - name: Deploying the infrastructure
        working-directory: ${{ env.working-directory }}
        run: |
          terraform init
          terraform plan
          # terraform apply --auto-approve
